<template>
  <section class="create-page">
    <div class="home-title">
      <h1>Create Stunning AI Art</h1>
          </div>
          <div>      <p class="text-center" style="text-align: center;">Explore a collection of imaginative and visually stunning images generated by DALL-E AI.</p>
          </div>

    <form @submit.prevent="handleSubmit" class="form-container">
      <!-- Name Input -->
      <div class="input-wrapper">
        <label for="name">Your Name</label>
        <input
          type="text"
          id="name"
          name="name"
          placeholder="Your Name"
          v-model="form.name"
          required
        />
      </div>

      <!-- Prompt Input and Actions -->
      <div class="input-wrapper prompt-container">
        <label for="prompt">Prompt</label>
        <div class="prompt-actions">
          <input
            type="text"
            id="prompt"
            name="prompt"
            placeholder="Enter your creative prompt"
            v-model="form.prompt"
            required
          />
          <button type="button" @click="generatePrompts" class="btn-secondary">
            Surprise Me
          </button>
          <button type="button" @click="generateImage" class="btn-primary">
            {{ generatingImg ? "Generating..." : "Generate" }}
          </button>
        </div>
      </div>

      <!-- Image Preview: ONLY Show After Generate Button Click -->
      <div v-if="generatingImg || form.photo" class="image-preview">
        <div class="img-container">
          <img :src="form.photo" v-if="form.photo" :alt="form.prompt" />
          <div v-else class="loader-overlay">
            <div class="loader"></div>
          </div>
        </div>
      </div>

      <!-- Share Button -->
      <div v-if="form.photo" class="share-container">
        <p>Once satisfied with your creation, share it with the community!</p>
        <button type="submit" class="btn-primary">
          {{ loading ? "Sharing..." : "Share with the Community" }}
        </button>
      </div>
    </form>
  </section>
</template>



<script setup>
import { reactive, ref } from 'vue';
import { getRandomPrompts } from '../utils';
import { useRouter } from 'vue-router';

const router = useRouter();

// Reactive form data
const form = reactive({
  name: '',
  prompt: '',
  photo: null, // No placeholder or image initially
});

const loading = ref(false);
const generatingImg = ref(false);

// Generate a random prompt
const generatePrompts = () => {
  const randomPrompt = getRandomPrompts();
  form.prompt = randomPrompt;
};

// Generate an image
const generateImage = async () => {
  if (form.prompt) {
    try {
      generatingImg.value = true;
      form.photo = null; // Clear any existing image

      const response = await fetch('https://texttoimageapi.themadhvi.com/api/v1/dalle', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt: form.prompt }),
      });

      const data = await response.json();

      if (data.photo) {
        form.photo = `data:image/jpeg;base64,${data.photo}`;
      } else {
        alert('Failed to generate an image. Please try again.');
      }
    } catch (error) {
      alert('An error occurred during image generation.');
      console.error(error);
    } finally {
      generatingImg.value = false;
    }
  }
};

// Submit the generated image
const handleSubmit = async () => {
  if (form.photo && form.name) {
    try {
      loading.value = true;

      const response = await fetch('https://texttoimage.themadhvi.com/api/v1/post', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: form.name,
          prompt: form.prompt,
          photo: form.photo,
        }),
      });

      if (response.ok) {
        alert('Image shared successfully!');
        router.push({ name: 'home' });
      } else {
        alert('Failed to share the image.');
      }
    } catch (error) {
      alert('An error occurred during submission.');
      console.error(error);
    } finally {
      loading.value = false;
    }
  } else {
    alert('Please generate an image before sharing.');
  }
};
</script>



<style scoped>
/* General Page Styles */
.create-page {
  padding: 40px 20px;
  font-family: "Arial", sans-serif;
  background: linear-gradient(to bottom, #ffffff, #f9f9f9);
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  border-radius: 12px;
  max-width: 800px;
  margin: 20px auto;
}

.text-center {
  text-align: center;
  color: #666464;
}

/* Header */
.home-title {
  text-align: center;
  margin-bottom: 30px;
}
.home-title h1 {
  font-size: 2.5rem;
  font-weight: bold;
  color: #444; /* Updated color */
}
.home-title p {
  font-size: 1rem;
  color: #444;
  margin-top: 10px;
}

/* Form Container */
.form-container {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

/* Input Styles */
.input-wrapper {
  display: flex;
  flex-direction: column;
}
label {
  margin-bottom: 8px;
  font-weight: bold;
  color: #444;
}
input[type="text"] {
  padding: 12px 14px;
  font-size: 1rem;
  border: 1px solid #6AC678; /* Updated color */
  border-radius: 6px;
  outline: none;
  transition: border-color 0.3s;
}
input[type="text"]:focus {
  border-color: #6AC678; /* Updated color */
}

/* Prompt Actions */
.prompt-container {
  display: flex;
  flex-direction: column;
}
.prompt-actions {
  display: flex;
  gap: 10px;
  align-items: center;
}
.prompt-actions input {
  flex: 1;
}
.btn-primary,
.btn-secondary {
  padding: 10px 16px;
  font-size: 1rem;
  border: none;
  border-radius: 6px;
  cursor: pointer;
  transition: background-color 0.3s, transform 0.2s;
}
.btn-primary {
  background-color: #6AC678; /* Updated color */
  color: #fff;
}
.btn-primary:hover {
  background-color: #5CB567; /* Slightly darker green */
  transform: scale(1.05);
}
.btn-secondary {
  background-color: #f0f0f0;
  color: #444;
}
.btn-secondary:hover {
  background-color: #e0e0e0;
  transform: scale(1.05);
}

/* Image Preview */
.image-preview {
  display: flex;
  justify-content: center;
  align-items: center;
  margin: 20px 0;
}
.img-container {
  position: relative;
  background-color: #f3f3f3;
  border: 2px dashed #6AC678; /* Updated color */
  border-radius: 8px;
  padding: 20px;
  max-width: 512px;
  max-height: 512px;
  display: flex;
  justify-content: center;
  align-items: center;
  overflow: hidden;
}
.img-container img {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
}
.loader-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(255, 255, 255, 0.8);
  display: flex;
  justify-content: center;
  align-items: center;
}
.loader {
  border: 4px solid rgba(0, 0, 0, 0.1);
  border-top: 4px solid #6AC678; /* Updated color */
  border-radius: 50%;
  width: 40px;
  height: 40px;
  animation: spin 1s linear infinite;
}
@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

/* Share Button */
.share-container {
  text-align: center;
  margin-top: 30px;
}
.share-container p {
  margin-bottom: 10px;
  color: #444;
}
</style>
