<template>
  <section class="create-page">
    <div class="home-title">
      <h1>Create</h1>
      <p>Browse through a collection of imaginative and visually stunning images generated by Dalle-E AI</p>
    </div>

    <form @submit.prevent="handleSubmit">
      <div class="flex">
        <!-- Name Input -->
        <div class="input-wrapper">
          <div class="label-container">
            <label for="name">Your Name</label>
          </div>
          <input type="text" id="name" name="name" placeholder="Your Name" v-model="form.name" required autocomplete="name">
        </div>

        <!-- Prompt Input and Surprise Me Button -->
        <div class="input-wrapper">
          <div class="label-container flex-between">
            <label for="prompt">Prompt</label>
            <button type="button" @click="generatePrompts">Surprise me</button>
          </div>
          <input type="text" id="prompt" name="prompt" placeholder="Do wonders" v-model="form.prompt" required autocomplete="off">
        </div>

        <!-- Image Preview -->
        <div class="img preview flex justify-center items-center">
          <img :src="form.photo" v-if="form.photo" :alt="form.prompt" class="img" />
          <img :src="preview" v-else alt="Preview" class="img" />
          
          <!-- Loader overlay for image preview -->
          <div v-if="generatingImg" class="loader-overlay flex justify-center items-center">
            <div class="loader"></div>
          </div>
        </div>

        <!-- Generate Button -->
        <div class="generate-btn flex">
          <button type="button" @click="generateImage">
            {{ generatingImg ? 'Generating...' : 'Generate' }}
          </button>
        </div>

        <!-- Share Button and Loader -->
        <div class="sharing-btn">
          <p>Once you have created the image you want, you can share it with the community.</p>
          <button type="submit">
            {{ loading ? 'Sharing...' : 'Share with the community' }}
          </button>
          
          <!-- Loader shows when sharing the image -->
          <div v-if="loading" class="loader-overlay flex justify-center items-center">
            <div class="loader"></div>
          </div>
        </div>
      </div>
    </form>
  </section>
</template>

<script setup>
import { reactive, ref } from 'vue';
import { preview } from '../assets';  // Default preview image
import {getRandomPrompts} from '../utils'
import { useRoute, useRouter } from 'vue-router';
const router=useRouter();
// Form data reactive object
const form = reactive({
  name: '',
  prompt: '',
  photo: ''
});

const loading = ref(false);
const generatingImg = ref(false);


const generatePrompts=()=>{
const randomPromt=getRandomPrompts(form.prompt)
form.prompt=randomPromt
};
// Function to generate a random prompt


// Form validation to check if fields are filled
const validateForm = () => {
  if (!form.name || !form.prompt) {
    alert('Please fill out all fields!');
    return false;
  }
  return true;
};

// Simulate image generation on button click
// const generateImage = async () => {
//   if (form.prompt) {
//     try {
//       generatingImg.value = true;
//       const response = await fetch('http://localhost:8000/api/v1/dalle', {
//         method: 'POST',
//         headers: {
//           "Content-Type": "application/json",
//         },
//         body: JSON.stringify({
//           prompt: form.prompt,
//         })
//       });

//       const data = await response.json();
      
//       if (data.photo) {
//         form.photo = `data:image/jpeg;base64,${data.photo}`;
//       } else {
//         alert("Image could not be generated. Try using a different prompt.");
//       }
//     } catch (error) {
//       alert("An error occurred during image generation. Please try again.");
//       console.error("Exception occurred during image generation:", error);
//     } finally {
//       generatingImg.value = false;
//     }
//   }
// };


const generateImage = async () => {
  if (form.prompt) {
    try {
      generatingImg.value = true;
      
      // Preprocess user input
      let prompt = form.prompt.trim(); // Trim whitespace

      // First attempt with the user prompt
      let response = await fetch('http://localhost:8000/api/v1/dalle', {
        method: 'POST',
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt })
      });

      let data = await response.json();

      if (data.photo) {
        form.photo = `data:image/jpeg;base64,${data.photo}`;
      } else {
        // If user prompt fails, fallback to a predefined prompt
        alert("Custom prompt failed to generate an image. Trying a random prompt...");
        
        // Use a random prompt from the constants file
        const randomPrompt = getRandomPrompts(form.prompt);
        form.prompt = randomPrompt;
        
        // Retry with the random prompt
        response = await fetch('http://localhost:8000/api/v1/dalle', {
          method: 'POST',
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ prompt: randomPrompt })
        });

        data = await response.json();
        form.photo = `data:image/jpeg;base64,${data.photo}`;
      }
    } catch (error) {
      alert("An error occurred during image generation. Please try again.");
      console.error("Exception occurred during image generation:", error);
    } finally {
      generatingImg.value = false;
    }
  }
};

const handleSubmit = async () => {
  if (form.prompt && form.photo) {
    try {
      loading.value = true;
      const response = await fetch('http://localhost:8000/api/v1/post', {
        method: 'POST',
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          prompt:form.prompt,
        name:form.name,
      photo: form.photo
        })
      });

      await response.json();
    
      router.push({name:"home"});
      
    } catch (error) {
      alert("An error occurred");
      console.error("Exception occurred during sharing the image:", error);
    } finally {
      loading.value = false;
    }
  }
};






</script>

<style scoped>
.create-page {
  padding: 20px;
}

.home-title {
  text-align: center;
  margin-bottom: 20px;
}

.flex {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.input-wrapper {
  display: flex;
  flex-direction: column;
}

.label-container {
  margin-bottom: 8px;
}

.label-container.flex-between {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

input[type="text"] {
  padding: 10px;
  font-size: 1rem;
  border: 1px solid #ccc;
  border-radius: 4px;
}

button {
  padding: 10px 20px;
  font-size: 1rem;
  background-color: #3498db;
  color: white;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

button:hover {
  background-color: #2980b9;
}

.img.preview {
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  background-color: #f3f3f3;
  border: 1px solid #ccc;
  border-radius: 4px;
  /* Remove fixed height to let the image determine the container's size */
  height: auto;
  width: auto;
  max-width: 512px; /* Optional: Set max width if needed */
  max-height: 512px; /* Optional: Set max height if needed */
  padding: 0; /* Remove any padding */
  opacity: 1; /* Ensure full opacity */
}

.img {
  max-height: 100%;
  max-width: 100%;
  object-fit: contain;
  /* Remove extra styling to avoid constraints */
}


.loader {
  border: 4px solid rgba(0, 0, 0, 0.1);
  border-left-color: #3498db;
  border-radius: 50%;
  width: 50px;  /* Adjust size if needed */
  height: 50px;
  animation: spin 1s linear infinite;
}

@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}

.loader-overlay {
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  justify-content: center;
  align-items: center;
  background: rgba(255, 255, 255, 0.7);  /* Slight opacity to overlay the loader on image */
}

.generate-btn,
.sharing-btn {
  display: flex;
  justify-content: center;
  align-items: center;
  margin-top: 20px;
}

.sharing-btn p {
  margin-bottom: 10px;
  text-align: center;
}
</style>
