<template>
<section>
    <div class="home-title">
        <h1>The community showcase</h1>
        <p>Browse through a collection of imaginative and visually stunning images generated by Dalle-E AI</p>
    </div>

    <div class="search-input">
        <div class="input-wrapper">
            <div class="label-container">
                <label for="text">Search Posts</label>
            </div>
            <input type="text" id="text" name="text" placeholder="search something..." v-model="searchText" required>
        </div>
    </div>
    <div class="mt-10">
        <div class="flex-justify-center items-center" v-if="loading">
            <p>It's Loading</p>
        </div>
        <div v-else>
            <h2 v-if="searchText" class="search-text">
                Showing Results for <span>{{searchText}}</span>
            </h2>
            <div class="cards-wrapper">
                <template v-if="filteredPost?.length > 0">
                    <!----<Card v-for="(post,i) in filteredPost" :post="post" :key="index"/>-->

                    <Card v-for="(post, i) in filteredPost" :post="post" :key="i" />

                </template>

                <h2 v-else class="title">
                    {{ title }}
                </h2>
            </div>
        </div>
    </div>
</section>
</template>

<script setup>
import Card from '@/components/card.vue';
import { computed, onMounted, ref } from 'vue';

const searchText=ref('')
const loading=ref(false)
const allPosts=ref([]);
const title=ref('')

// const fetchPosts = async () => {
//   if (form.prompt && form.photo) {
//     try {
//       loading.value = true;
//       const response = await fetch('http://localhost:8000/api/v1/post', {
//         method: 'GET',
//         headers: {
//           "Content-Type": "application/json",
//         }
//       });
// const result=  await response.json();
// allPosts.value=result.data.reverse();
// if(result.data.length==0){
//     title.value='No Posts Yet'
// }
      
//     } catch (error) {
//       alert("An error occurred",error);
//       console.error("Exception occurred during sharing the image:", error);
//     } finally {
//       loading.value = false;
//     }
//   }
// };

const fetchPosts = async () => {
  try {
    loading.value = true;
    const response = await fetch('http://localhost:8000/api/v1/post', {
      method: 'GET',
      headers: {
        "Content-Type": "application/json",
      }
    });
    const result = await response.json();
    allPosts.value = result.data.reverse();
    if (result.data.length === 0) {
      title.value = 'No Posts Yet';
    }
  } catch (error) {
    alert("An error occurred", error);
    console.error("Exception occurred during sharing the image:", error);
  } finally {
    loading.value = false;
  }
};
// const filteredPost=computed(()=>{
//     if(searchText.value==''){
//         return allPosts.value
//     }
//     else{
//         const result=allPosts.value.filter((item)=> item.name.toLowerCase().includes(searchText.value.toLowerCase())
//     ||item.prompt.toLowerCase().includes(searchText.value.toLowerCase()));
//     if (result.data.length === 0) {
//       title.value = 'No Search Results Found';
//     };
//     return result

//     }
// });

const filteredPost = computed(() => {
  // If there is no search text, show all posts
  if (!searchText.value) {
    return allPosts.value || []; // Ensure allPosts is an array
  }

  // Filter posts based on search text
  const result = allPosts.value
    ? allPosts.value.filter(
        (item) =>
          item.name.toLowerCase().includes(searchText.value.toLowerCase()) ||
          item.prompt.toLowerCase().includes(searchText.value.toLowerCase())
      )
    : []; // Default to empty array if allPosts is undefined

  // Update title if no results are found
  if (result.length === 0) {
    title.value = 'No Search Results Found';
  }

  return result;
});


onMounted(async()=>{
await fetchPosts()})


</script>